Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.7.15/x64/lib/python3.7/site-packages/jupyter_cache/executors/utils.py", line 56, in single_nb_execution
    record_timing=False,
  File "/opt/hostedtoolcache/Python/3.7.15/x64/lib/python3.7/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/opt/hostedtoolcache/Python/3.7.15/x64/lib/python3.7/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/opt/hostedtoolcache/Python/3.7.15/x64/lib/python3.7/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/opt/hostedtoolcache/Python/3.7.15/x64/lib/python3.7/asyncio/base_events.py", line 587, in run_until_complete
    return future.result()
  File "/opt/hostedtoolcache/Python/3.7.15/x64/lib/python3.7/site-packages/nbclient/client.py", line 664, in async_execute
    cell, index, execution_count=self.code_cells_executed + 1
  File "/opt/hostedtoolcache/Python/3.7.15/x64/lib/python3.7/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/opt/hostedtoolcache/Python/3.7.15/x64/lib/python3.7/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
from compiam.melody import DEEPSRGM
deepsrgm = DEEPSRGM()  # initializing a melodia instance
feat = deepsrgm.get_features(from_mirdata=True, track_id="TODO")
deepsrgm.predict(feat)

------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mTypeError[0m                                 Traceback (most recent call last)
[0;32m/tmp/ipykernel_3104/4025964489.py[0m in [0;36m<module>[0;34m[0m
[1;32m      1[0m [0;32mfrom[0m [0mcompiam[0m[0;34m.[0m[0mmelody[0m [0;32mimport[0m [0mDEEPSRGM[0m[0;34m[0m[0;34m[0m[0m
[0;32m----> 2[0;31m [0mdeepsrgm[0m [0;34m=[0m [0mDEEPSRGM[0m[0;34m([0m[0;34m)[0m  [0;31m# initializing a melodia instance[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m      3[0m [0mfeat[0m [0;34m=[0m [0mdeepsrgm[0m[0;34m.[0m[0mget_features[0m[0;34m([0m[0mfrom_mirdata[0m[0;34m=[0m[0;32mTrue[0m[0;34m,[0m [0mtrack_id[0m[0;34m=[0m[0;34m"TODO"[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m      4[0m [0mdeepsrgm[0m[0;34m.[0m[0mpredict[0m[0;34m([0m[0mfeat[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m

[0;31mTypeError[0m: __init__() missing 2 required positional arguments: 'model_path' and 'mapping_path'
TypeError: __init__() missing 2 required positional arguments: 'model_path' and 'mapping_path'

